#!/bin/bash

# TODO add even/odd line option? not supported in BSD sed
# TODO add flag for if - is negative or 1,i?

usage="usage: $0 [-t -h] command filerange
-t: test, dry run, just print what would be run
-h: display this help
filerange: comma or space separated line numbers from git status,
ranges are also supported in the form x-y, or x-
x- goes from line number x to the end(equivalent to x-$)
negative indices are also supported"

if [[ $# -lt 2 ]]
then
	echo "$usage"
	exit
fi

args=()

while [ "$1" ]
do
	case $1 in
		-h)
			echo "$usage"
			exit
			;;
		-t)
			dry=true
			;;
		*)
			args=(${args[@]} $1)
			;;
	esac
	shift
done

len=$(git status --porcelain |
wc -l)

command=${args[0]}
args=(${args[@]:1})

items=$(echo "${args[@]}"			|
# deal with csv
tr ',' ' '							|
tr ' ' '\n'							|
# deal with ranges
sed 's/\([0-9]\)-\([0-9$]\)/\1,\2/'	|
# deal with ranges without an end
sed 's/\([0-9]\)-/\1,$/'			|
# negative indices
awk -v len="$len" '{print ($1 < 0) ? (len + $1 + 1) : $1}'
)

for i in $items
do
	# make sure index is in range
	if [[ $i =~ [0-9]+$ && ( $i -gt $len || $i -le 0 ) ]]
	then
		echo -n "$i is out of range!"
		echo " $len changed file$([[ $len -gt 1 ]] && echo s)"
		exit
	fi
	if [[ $i =~ [0-9]+ ]]
	then
		# otherwise add to list
		indices="$indices${i}p;"
	else
		command="$command $i"
	fi
done

command="git $command $(
# get an easily parsed format
git status --porcelain							|
# filter out already added files
grep -v "^A"									|
# get rid of prepended symbols
cut -c4-										|
# print out the requested lines
sed -n "$indices"								|
# convert back into an arg list
tr '\n' ' ')"

if [[ $dry ]]
then
	echo "$command"
else
	eval "$command"
fi
