#!/bin/bash

function get-parentbranch {
    # might be fragile
    git log --graph --decorate --simplify-by-decoration --oneline | grep "origin/HEAD" | grep -o "\((.*)\)" | sed 's/[()]//g' | awk '{print $NF}'
}

function get-current-branch {
	git branch | awk '/*/{print $2}'
}

gh pr create -H $(get-current-branch) -df $([[ -n "$1" ]] && echo " -b '$1'")