#!/bin/bash
# git rerequest review if checks have passed

# would be better it the team worked in gh, but alas

function parse-args {
	options=$(getopt -o ron:hva:c:dtb:pswe --long "review,open,number:,help,verbose,add:,comment:,draft,test,body:,push,show,view,team" -- "$@")
	eval set -- "$options"

	function usage {
		echo -e "Usage: $(basename $0) [options]"
		echo
		echo -e "Options:
	-n, --number <pr_number>\tSpecify the pull request number
	-r, --review\tRe-request review from last reviewers, i.e., ones that reviewed since last request
	-o, --open\tOpen the review from draft
	-v, --verbose\tEnable verbose mode
	-a, --add <reviewer>\tAdd a reviewer
	-c, --comment <comment>\tAdd a comment after checks pass
	-d, --draft\tCreate a draft pull request
	-t, --test\tTest mode (echo commands instead of executing)
	-b, --body <body>\tSpecify the body content for pr description, newline and tab characters will be resolved for actual use
	-p, --push\tPush changes
	-h, --help\tDisplay this help message
	-s, --show\tShow the pr
	-w, --view\tView the pr in the browser,
	-e, --team\tAdd a team to the pr
	" |
	column -ts$'\t'
	}
	# parse arguments
	while true; do
		case "$1" in
			-h|--help)
				usage
				exit 1
				;;
			-n|--number)
				pr_number=$2
				shift 2
				;;
			-r|--review)
				rerequest_review=true
				shift
				;;
			-o|--open)
				open_review=true
				shift
				;;
			-v|--verbose)
				verbose=true
				shift
				;;
			-a|--add)
				# reviewers=$2
				[[ ! $2 ]] && echo "No reviewer specified" && exit 1
				if [[ "$2" =~ .*,.* ]]
				then
					readarray -td, reviewers <<<"$2"
				else
					reviewers+=($2)
				fi
				# readarray -td, a <<<"$2"; declare -p reviewers;
				shift 2
				;;
			-c|--comment)
				comment=$2
				shift 2
				;;
			-d|--draft)
				draft=true
				shift
				;;
			-t|--test)
				vecho=echo
				shift
				;;
			-b|--body)
				body="$(echo -e $2)"
				shift 2
				;;
			-p|--push)
				push=true
				shift
				;;
			-w|--view)
				view=true
				shift
				;;
			-s|--show)
				show=true
				shift
				;;
			-e|--team)
				team=true
				shift
				;;
			--)
				shift
				break
				;;
			*)
				echo "unsupported flag $1"
				exit 1
				;;
		esac
	done
}

reviewers=()
rereviewers=()
parse-args "$@"
# todo add abliity to pass in custom function, e.g., open review when checks pass, but also add a comment
#x todo add ability to make draft, wait for checks, then open review
teamMembers=("ardove" "czf-veradigm" "aaronmr5" "tylerstarcher")

function join-array { local IFS=","; echo "$*"; }

function get-reviewers {
	# todo doesn't seem to be working, check flow
	uniqReviewers=($(echo ${reviewers[@]} | tr ' ' '\n' | sort -u | tr '\n' ' '))
	[[ $verbose ]] && echo "uniq Reviewers array: ${uniqReviewers[@]}" >&2
	join-array ${uniqReviewers[@]}
}

# todo this isn't actually pulling reviewers correctly now, see what's going on
function reopen_review {
	# filter requires better logic because it seems to list people multiple times if their review was, for example, dismissed and then requested again and they approved
	# this should work for people since last review, should be good enough
	output=$(gh pr view $pr_number --json latestReviews -q "[
		.latestReviews[] |
		select(.author.login != \"$(git config user.name)\" and
		(.state == \"DISMISSED\" or .state == \"COMMENTED\" or .state == \"APPROVED\"))
	] |
	map(.author.login) |
	join(\",\")")
	# echo "output: $output"
	# echo $output |
	# read -td, rereviewers
	# declare -a rereviewers
	IFS="," read -r -d $'\n' -a rereviewers <<< "$output"
	reviewers+=("${rereviewers[@]}")
	[[ $verbose ]] && echo "ReReviewers array: ${rereviewers[@]}" >&2
	[[ $verbose ]] && echo "new Reviewers array: ${reviewers[@]}" >&2
	[[ $verbose ]] && echo "(Re)Reviewers: $(get-reviewers)" >&2
	$vecho gh pr edit $pr_number --add-reviewer "$(get-reviewers)"
}

#? move adding reviewers outside of opening pr? could be useful to do something like what chris did and have reviewers on a draft while other dependent prs are being reviewed
function open_review {
	$vecho gh pr ready $pr_number
}

[[ $team ]] && reviewers+=("${teamMembers[@]}")

if [[ -n $verbose ]]
then
	outfile=/dev/stdout
	# echo flag values
	echo "pr_number: ${pr_number-current branch}
rerequest_review: ${rerequest_review-false}
open_review: ${open_review-false}
verbose: ${verbose-false}
reviewers: $(get-reviewers)
comment: '$comment'
draft: ${draft-false}
body: '$body'
push: ${push-false}
view: ${view-false}
show: ${show-false}
team: ${team-false}"
else
	outfile=/dev/null
fi

(
	(
		[[ $draft ]] && $vecho git pushdraft "\"$body\"" &&
		echo "Draft pushed, giving checks a chance to start before waiting on them"
	) ||
	(
		[[ $push ]] && $vecho git push &&
		echo "Pushed, giving checks a chance to start before waiting on them"
	)
) &&
# sleep for a second to give checks a chance to start
sleep 5

# todo loop to check if checks have started? then just capture response code for check?

# this should wait for the checks to finish and fail if any of them fail
if [[ $vecho ]] || gh pr checks --watch --fail-fast > $outfile
then
	echo "Checks have passed"

	# this is currenlty common between flows, so don't require one to be triggered to add it
	[[ $comment ]] && $vecho gh pr comment $pr_number -b "$comment"

	if [[ -n $rerequest_review ]]
	then
		echo "requesting review"
		reopen_review
	elif [[ -n $open_review ]]
	then
		echo "opening pr"
		open_review
	fi

	#? is this also desired if nothing is happening with the pr? seems ok, can make a draft and add reviewers, then open it when really ready
	#? should this only be when not requesting rereview since that will pull the reviewers array?
	if [[ $reviewers ]] && [[ -z $rerequest_review ]]
	then
		$vecho gh pr edit $pr_number --add-reviewer "$(get-reviewers)"
	fi

	[[ $view ]] && gh pr view $pr_number --web
	[[ $show ]] && gh pr view $pr_number
else
	echo "Checks have failed, not requesting review"
	exit 1
fi